theme: minima

# site details
title: Naman Chauhan, Techmirtz
author: Naman Chauhan
email: chauhannaman98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Naman Chauhan, also known as techmirtz. A UG student, embedded systems developer, C/C++ programmer,
  tech enthusiast, public speaker.

# social links
twitter_username: techmirtz # DO NOT include the @ character, or else the build will fail!
github_username:  chauhannaman98 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
